// Angular/src/app/hotel/add-hotel/add-hotel.component.ts
import { hotel } from '../../model/models';
import { Component, OnInit } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { ToastrService } from 'ngx-toastr';
import { HotelService } from '../../services/hotel.service';
import { Router } from '@angular/router';
import {selectValidator} from "../../shared/select.validator"
import { StorageService } from 'src/app/services/storage.service';

@Component({
  selector: 'app-add-hotel',
  templateUrl: './add-hotel.component.html',
  styleUrls: ['./add-hotel.component.css']
})

export class AddHotelComponent implements OnInit{
  constructor(private fb:FormBuilder,private toast:ToastrService,private _hotel:HotelService,private router: Router,private _userStore:StorageService){}
  ngOnInit(): void {
      this._hotel.editFlag.subscribe((data)=>{
        this.editFlag = data
      })
      if(this.editFlag){
       this.editingHotel =  this._hotel.getEditHotel()
      }
      
      this.editHotel()
  }
  editFlag:boolean= false
  editingHotel:hotel | undefined;
  image:any;
  getImage(event:any){
    if(event.target.files.length > 0){
      this.image = event.target.files[0];
    }
  }
  get name():any{
    return this.addHotel.get('name');
  }
  get city():any{
    return this.addHotel.get('city');
  }
  get address():any{
    return this.addHotel.get("address");
  }
  get category():any{
    return this.addHotel.get("category");
  }
  get price():any{
    return this.addHotel.get("price");
  }

  // get amenities():any{
  //   return this.addHotel.get("amenities");
  // }
  addHotel:any = this.fb.group({
    name: ["",[Validators.required,Validators.maxLength(25)]],
    city: ["",[Validators.required,Validators.maxLength(25)]],
    image:[""],
    address:["",[Validators.required,Validators.maxLength(200)]],
    category: [0,[Validators.required,selectValidator]],
    price:["",[Validators.required,Validators.min(1)]],
    Amenities: this.fb.group({
             wifi : [false],
             concierge : [false],
             parking : [false],
             dumbbell :[false] ,
             spa : [false],
             pool : [false]
    })
  })

  //  Editing hotel
  editHotel(){
    if(this.editFlag){
      console.log("editing")
      console.log(this.editingHotel)
      this.addHotel.patchValue(this.editingHotel);
    }
  }
  onSubmit(){
    let values = this.addHotel.value

    if(!this.editFlag){
    const formData = new FormData();
    console.log(values)
    for ( var key in values) {
      if(key === "image"){
        continue;
      }
      if(key === "Amenities"){
        let amenities = JSON.stringify(values[key])
        formData.append(key, amenities);
        continue;
      }
      formData.append(key, values[key]);
     }
     formData.append("image",this.image)

    this._hotel.addHotel(formData).subscribe({
      next:(data:any) =>{
        this.toast.success(`Hotel successfully added`)
        this.addHotel.reset();
      },
      error:error => {
        if (error.error) {
          if (error.status === 401) {
            this.router.navigate(['/login'])
            this.toast.error("session expired login again", `${error.error.message}`)
            this._userStore.logOut()
          }else{
            this.toast.error(`${error.error.message}`)
          }
        }
      }
    }

    )}
    else{
      delete this.addHotel.value.image
      if(this.image){
      const formData = new FormData();
      formData.append("image",this.image)
      this._hotel.uploadImage(formData,this.editingHotel?.id).subscribe((data)=>{
      })
    }
      this._hotel.updateHotel(this.addHotel.value).subscribe({
        next:(data:any) =>{
          this.toast.success(`Hotel successfully updated`)
          this.addHotel.reset();
          this._hotel.editFlag.next(false)
        },
        error:error => { if (error.error) {
          if (error.status === 401) {
            this.router.navigate(['/login'])
            this.toast.error("session expired login again", `${error.error.message}`)
            this._userStore.logOut()
          } else {
            this.toast.error(`${error.error.message}`)
          }
        }
        }
      })
    }
 
}
}

<div class="userforms">
  <h4>Add New Hotel</h4>

<form [formGroup] = "addHotel" (ngSubmit)="onSubmit()" novalidate>
    <div class="form-group mt-3">
      <label >Name:</label>
      <input  [class.is-invalid] = "name?.invalid && name?.touched" formControlName="name" type="text" class="form-control" placeholder="Enter name">
      <div *ngIf="name?.invalid && name?.touched">
            <small [class.d-none]="!name?.errors?.['required'] " class="text-danger">name is required</small>
            <small *ngIf="!name?.errors?.['maxLength'] " class="text-danger">max length is 25 character </small>

      </div>
    </div>
      
  
    <div class="form-group mt-3" >
      <label>city</label>

      <input  [class.is-invalid] = "city?.invalid && city?.touched"  formControlName="city"  class="form-control" type="text"  placeholder="Enter city">
      <div *ngIf="city?.invalid && city?.touched">
        <small *ngIf="city?.errors?.['required']" class="text-danger">city is required </small>
        <small *ngIf="city?.errors?.['maxLength'] " class="text-danger">max length is 25 character </small>
     </div>
    </div>
  
   
    <div class="form-group mt-3">

      <label>Address</label>
      <input  [class.is-invalid] = "address?.invalid && address?.touched" formControlName="address" type="text" class="form-control"  placeholder="Enter full address">
      <div *ngIf="address?.invalid && address?.touched">
         <small *ngIf="address?.errors?.['required']" class="text-danger">Address is required </small>
         <small *ngIf="address?.errors?.['maxLength'] " class="text-danger">max length is 200 character </small>

      </div>
    </div>

    <div class="form-group mt-3">
        <label>category</label>
       
        <!-- <input   [class.is-invalid] = "category?.invalid && category?.touched" formControlName="category" type="number" class="form-control"> -->
        <select class="form-control" formControlName="category" >
            <option value= 0 selected>select category  </option>
            <option value= 3 > 3 Star</option>
            <option value= 4 > 4 Star  </option>
            <option value= 5 > 5 Star  </option>
          </select>
        <div *ngIf="category?.invalid && category?.touched">
        <small *ngIf="category?.errors?.['wrong']" class="text-danger">category is required</small>
        </div>
      </div>

    <div class="form-group mt-3">
        <label>price</label>
        <input   [class.is-invalid] = "price?.invalid && price?.touched" formControlName="price" type="number" class="form-control"  placeholder="Enter price">
        <div *ngIf="price?.invalid && price?.touched">
        <small *ngIf="price?.errors?.['required']" class="text-danger">price is required</small>
        <small *ngIf="price?.errors?.['min']" class="text-danger">minimum price is 1 </small>

        </div>
      </div>
  
      <div class="form-group mt-3">
        <label >image</label>
        <input (change)="getImage($event)" accept="image/*"  formControlName="image" name="image" type="file" class="form-control">
      </div>
 <div formGroupName = "Amenities" class="amenities">
    
    <span id="amenities">Amenities</span>
    <div class="form-check mt-3">
      <label for="wifi">wifi</label>
      <input id="wifi" formControlName="wifi" type="checkbox" class="form-check-input" >
    </div>
  
    <div class="form-check mt-3" >
      <label for="concierge">Food</label>
      <input id="concierge" formControlName="concierge" type="checkbox" class="form-check-input">
    </div>
  
    <div class="form-check mt-3" >
        <label for="dumbbell">Gym</label>
        <input id="dumbbell" formControlName="dumbbell" type="checkbox" class="form-check-input">
      </div>

      <div class="form-check mt-3" >
        <label for="parking">parking</label>
        <input id="parking"  formControlName="parking" type="checkbox" class="form-check-input">
      </div>

      <div class="form-check mt-3" >
        <label for="spa">spa</label>
        <input id="spa" formControlName="spa" type="checkbox" class="form-check-input">
      </div>

      <div class="form-check mt-3" >
        <label for="pool">pool</label>
        <input id="pool" formControlName="pool" type="checkbox" class="form-check-input">
      </div>
      
  </div>
    <button [disabled]="!addHotel.valid"  class="btn dark mt-3 " type="submit">Add</button> 
  </form>
</div>

// React/src/pages/hotels/addHotel.jsx
import {Formik,Form} from 'formik'
import * as Yup from 'yup';
import Input from '../../components/reusables/field';
import Btn from '../../components/reusables/button';
import FileUpload from '../../components/reusables/fileUpload';
// import Box from '@mui/material/Box';
import { TextField } from '@mui/material';
import SelectBox from '../../components/reusables/SelectBox';
import CheckBox from '../../components/reusables/checkBox';
import instance from '../../redux/axiosInstance';
import { ToastContainer } from 'react-toastify';
import notify from '../../components/reusables/toast';
import { useState } from 'react';
import Loader from '../../components/reusables/loader';

export default function AddHotel({editHotel}) {

    const [loader,setloader] = useState(false)
    const validationSchema = Yup.object().shape({
        name:Yup.string().required("required"),
        city:Yup.string().required("required"),
        address:Yup.string().required("required"),
        category:Yup.number().required("required"),
        price:Yup.number().required("required"),

    })
  return (
<div className='addHotelForm'>
    <h3>New Hotel</h3>
        <Formik
        initialValues = {!editHotel ? {name:"",city:"",address:"",category:"",price:"",image:"",Amenities:{
            wifi: true,
            concierge: false,
            parking: false,
            dumbbell: false,
            spa: false,
            pool: false,
        }} : editHotel}
        validationSchema = {validationSchema}
        onSubmit = {(values)=>{
            setloader(true)
            const formdata = new FormData();

            for(let key in values){
                console.log(key,values[key])
                if(key === "updatedAt"){
                    formdata.append(key,new Date())
                    continue;
                }
                if(key === "Amenities"){
                    formdata.append(key,JSON.stringify(values[key]))
                    continue;
                }
               formdata.append(key,values[key])
            }
            if(!editHotel){
            instance.post("hotel/addHotel",formdata)
            .then(()=>notify("successfully Added","success") ,  setloader(false)

            )
            .catch((error)=> notify(error.message,"error") ,  setloader(false)
            )
         }  else {
            
            instance.patch(`hotel/updateHotel/${editHotel.id}`,formdata).
            then(()=> notify("successfully Added","success"),  setloader(false))
            .catch((error)=> notify(error.message,"error") ,  setloader(false)
            )
         } 
            console.log(values)
           

        }}
        >
                  {({ setFieldValue,errors, touched }) => (
                    <Form>
                        <div>
                            <Input  Name={'name'} type={TextField} errors={errors} touched={touched} label={'Hotel Name'}  sx={{width:'100%'}}/>
                        </div>

                        <div>
                            <Input  Name={'city'} type={TextField} errors={errors} touched={touched} label={'city'}  sx={{width:'100%'}}/>
                        </div>

                        <div>
                            <Input  Name={'address'} type={TextField} errors={errors} touched={touched} label={'address'}  sx={{width:'100%'}}/>
                        </div>

                        <div>
                            <SelectBox  name={"category"} errors={errors} touched={touched} label={"Select Category"}/>
                        </div>

                        <div>
                            <Input  Name={'price'} type={TextField} errors={errors} touched={touched} label={'price'} type2={"number"}  sx={{width:'100%'}}/>
                        </div>

                        <div>
                            <FileUpload setFieldValue= {setFieldValue} />
                        </div>

                        <div className='AddAmenities'>
                            <div className='checkboxes' >Amenities</div>
                            
                                <CheckBox label={"wifi"} name={"wifi"} />
                                <CheckBox label={"dinner"} name={"concierge"} />
                                <CheckBox label={"parking"} name={"parking"} />
                                <CheckBox label={"gym"} name={"dumbbell"} />
                                <CheckBox label={"spa"} name={"spa"} />
                                <CheckBox label={"pool"} name={"pool"} />
                        </div>

                        <Btn  variant= 'contained' sx={{}} name = {'submit'}  type = {'submit'} />

                    <ToastContainer/>
                    </Form>
                  )}
        </Formik>
              {loader ? <Loader/> :null}
        </div>
    )
}
